// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtyqhrygzlhdtgngdtfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0eXFocnlnemxoZHRnbmdkdGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTU0MTMsImV4cCI6MjA2NjkzMTQxM30.LbtjilWObz4yVyevtKkNDNuf1zvHllRf1B-XxGPT5vY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});